language: elixir
elixir:
  - 1.6
otp_release:
  - 20.2
sudo: false
env:
  global:
    - ELIXIR_ASSERT_TIMEOUT=2000
  matrix:
    - COWBOY_VERSION=1.0
before_script:
  - mix deps.get
script:
  - mix test
